# Generated by Django 3.2.5 on 2021-08-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('location', models.CharField(max_length=255, verbose_name='居住地')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(blank=True, max_length=255, verbose_name='line_id 名稱')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='電子郵件')),
                ('tel', models.CharField(max_length=10, verbose_name='電話號碼')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('suggest', models.TextField(blank=True, max_length=500, verbose_name='建議')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='kinqston.customer', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '客戶意見與聯絡方式',
                'verbose_name_plural': '客戶意見與聯絡方式',
            },
        ),
    ]
